// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKo6J8aqSOKbvpXG_Ui6-pj8AyJjYnnOA',
    appId: '1:502842623718:android:c77e542e9fb486ad349d27',
    messagingSenderId: '502842623718',
    projectId: 'work-it-out-efcbc',
    databaseURL: 'https://work-it-out-efcbc-default-rtdb.firebaseio.com',
    storageBucket: 'work-it-out-efcbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeGAgDQ-kqEjcaJxvkJX_-PN9HY-gpHe8',
    appId: '1:502842623718:ios:3692d90cbe913924349d27',
    messagingSenderId: '502842623718',
    projectId: 'work-it-out-efcbc',
    databaseURL: 'https://work-it-out-efcbc-default-rtdb.firebaseio.com',
    storageBucket: 'work-it-out-efcbc.appspot.com',
    androidClientId:
        '502842623718-0jlgq33hnf9elh1lvjb2od7oongl074f.apps.googleusercontent.com',
    iosClientId:
        '502842623718-ibei4gk3o7931281qhailicp3midfp4l.apps.googleusercontent.com',
    iosBundleId: 'com.mayank.workout',
  );
}